### ISSUE TITLE
error: Could not compile `crfsuite-sys`

### ISSUE THREAD

**Issue by madeindjs** [snipsco/rustling-ontology#99] opened 2018-04-26 13:58 UTC
Trying to build the [weather example of snips-nlu-lib](https://github.com/snipsco/snips-nlu-rs/blob/develop/snips-nlu-lib/examples/weather.rs), I had the following error..

~~~bash
$ cargo run
   Compiling snips-nlu-resources-packed v0.55.2 (https://github.com/snipsco/snips-nlu-rs#6a48f869)
   Compiling crfsuite-sys v0.2.0-pre (https://github.com/snipsco/crfsuite-rs?rev=b18d95c#b18d95cf)
   Compiling rustling-ontology v0.17.0 (https://github.com/snipsco/rustling-ontology?tag=0.17.0#2efa4c01)
error: unexpected close delimiter: `]`
   --> /home/arousseau/dev/personnel/rust/test_snip/target/debug/build/crfsuite-sys-1b9f39ab8b7d8fbd/out/crfsuite.rs:201:32
    |
201 | #[derive(Copy, Clone)]; 4usize ] , _bindgen_union_align : u32 , }#[test]
    |                                ^
~~~

I just create a project with `cargo new --bin test_snip` and I had the following files

~~~toml
# Cargo.toml

[package]
name = "test_snip"
version = "0.1.0"

[dependencies]
snips-nlu-lib = { git = "https://github.com/snipsco/snips-nlu-rs", branch = "master" }
~~~

~~~rust
// src/main.rs
extern crate serde_json;
extern crate snips_nlu_lib;

use std::env;

use snips_nlu_lib::{FileBasedConfiguration, SnipsNluEngine};

fn main() {
    let args: Vec<String> = env::args().collect();
    let model_file = &args[1];
    let query = &args[2];
    let configuration = match FileBasedConfiguration::from_path(model_file, false) {
        Ok(conf) => conf,
        Err(e) => panic!(format!("{}", e)),
    };
    let nlu_engine = SnipsNluEngine::new(configuration).unwrap();

    let result = nlu_engine.parse(query, None).unwrap();

    println!("{}", serde_json::to_string_pretty(&result).unwrap());
}
~~~

**Comment by adrienball** [comment] 2018-05-03 08:42
Hi @madeindjs ,
Thanks for reporting this issue, it is actually not `rustling-ontology` which causes troubles but `crfsuite-sys` (dependency of `snips-nlu`). Anyway, I'll look at it and try to reproduce it.
Will keep you posted.

Cheers

**Comment by adrienball** [comment] 2018-05-04 14:54
@madeindjs 
I can't reproduce on my machine.
Can you give some environment info:
- OS ?
- Rust version ?
- Cargo version ?

Besides, have you run `rustfmt` at some point? If so, then it might related to this issue --> https://github.com/rust-lang-nursery/rust-bindgen/issues/1045

**Comment by adrienball** [comment] 2018-05-04 16:07
Thanks.
Besides, have you run `rustfmt` at some point? If so, then it might be related to this issue --> rust-lang-nursery/rust-bindgen#1045

**Comment by adrienball** [comment] 2018-10-23 09:45
I'm closing this issue since it is not related to `rustling-ontology`.

**Closed by adrienball** 2018-10-23 09:45 UTC
